name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "glacial-stream-16288"
          heroku_email: "balint.dolla@gmail.com"
        env:
          HD_MONGO_URI: ${{secrets.MONGO_URI}}