name: Deploy

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm run install:root      
      - name: Lint  
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "glacial-stream-16288"
          heroku_email: "balint.dolla@gmail.com"
        env:
          HD_MONGO_URI: ${{secrets.MONGO_URI}}